-- Bật extension pgcrypto nếu cần
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Table: profiles (dùng role mapping từ auth.users để làm Admin)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'user'::TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Table: campaigns
CREATE TABLE public.campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Giữ nguyên kiểu INT/BIGINT như MySQL cũ
  sponsor_name TEXT NOT NULL,
  sponsor_short TEXT NOT NULL,
  description TEXT DEFAULT 'TẶNG 1 LY NƯỚC'::TEXT,
  logo TEXT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  guide_content TEXT,
  menu_content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;

-- Table: vouchers
CREATE TABLE public.vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT REFERENCES public.campaigns(id) ON DELETE CASCADE NOT NULL,
  code TEXT NOT NULL,
  logo TEXT,
  status TEXT DEFAULT 'unused'::TEXT, -- 'unused', 'used', 'expired'
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  UNIQUE(campaign_id, code)
);
ALTER TABLE public.vouchers ENABLE ROW LEVEL SECURITY;

-- Table: free_vouchers
CREATE TABLE public.free_vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  sponsor_name TEXT,
  description TEXT DEFAULT 'TẶNG 1 LY NƯỚC'::TEXT,
  logo TEXT,
  start_date DATE,
  end_date DATE,
  guide_content TEXT,
  menu_content TEXT,
  status TEXT DEFAULT 'unused'::TEXT, -- 'unused', 'used', 'expired'
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);
ALTER TABLE public.free_vouchers ENABLE ROW LEVEL SECURITY;

-- Table: given_vouchers
CREATE TABLE public.given_vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT REFERENCES public.vouchers(id) ON DELETE CASCADE,
  given_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);
ALTER TABLE public.given_vouchers ENABLE ROW LEVEL SECURITY;

-- Table: taken_vouchers
CREATE TABLE public.taken_vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT REFERENCES public.campaigns(id) ON DELETE CASCADE,
  quantity BIGINT NOT NULL,
  taken_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);
ALTER TABLE public.taken_vouchers ENABLE ROW LEVEL SECURITY;

-- Simple Policies (Mở quyền SELECT tự do cho phép khách xem voucher không cần đăng nhập)
CREATE POLICY "Public profiles" ON profiles FOR SELECT USING (true);
CREATE POLICY "Public campaigns" ON campaigns FOR SELECT USING (true);
CREATE POLICY "Public vouchers" ON vouchers FOR SELECT USING (true);
CREATE POLICY "Public free_vouchers" ON free_vouchers FOR SELECT USING (true);
CREATE POLICY "Update own voucher" ON vouchers FOR UPDATE USING (true); -- Sẽ kiểm tra Role/API secret chặt hơn sau
CREATE POLICY "Update own free_voucher" ON free_vouchers FOR UPDATE USING (true);
